name: 'Plan build matrix from Node.js package.json file'
description:
  "Automatically determine supported Node.js versions and GitHub Actions runners
  from the contents of your project's package.json file."
author: 'nasa-gcn'

outputs:
  nodeVersion:
    description: 'Array of values for actions/setup-node node-version input'
  runsOn:
    description: 'Array of values for jobs.<job_id>.steps[*].run'

runs:
  using: node20
  main: dist/index.js
